[[zones]]
zone = "example.com"
zone_type = "Primary"
axfr_policy = "AllowAll"

[zones.stores]
type = "sqlite"
zone_path = "example.com.zone"
journal_path = "example.com.journal"
allow_update = true

[[zones.stores.tsig_keys]]
name = "example.com."
key_file = "example.com.key"
algorithm = "hmac-sha256"
